[book]

title = "Rust 参考手册 - The Rust Language Reference"
authors = ["minstrel1977"]
language = "zh"
description = "rust reference 中文, Rust 参考手册"

[output.html]
additional-css = ["theme/reference.css"]
git-repository-url = "https://gitee.com/minstrel1977/rust-reference"
edit-url-template = "https://github.com/rust-lang/reference/edit/master/{path}"

[output.html.redirect]
"/expressions/enum-variant-expr.html" = "struct-expr.html"
"/unsafe-blocks.html" = "unsafe-keyword.html"
"/unsafe-functions.html" = "unsafe-keyword.html"

[rust]
edition = "2021"
